x = input('Enter your name: ')
y = int(input('Enter your age: '))
print('Dear %s , you will be of 100 years after %i'%(x,100-y))
num = int(input('Enter any number: '))
print('\nDear %s , you will be of 100 years after %i'%(x,100-y)*num)
